// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package protobuffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApplyLogRequest struct {
	CurrentCommitID      int64                `protobuf:"varint,1,opt,name=currentCommitID" json:"currentCommitID,omitempty"`
	CurrentTermID        int64                `protobuf:"varint,2,opt,name=currentTermID" json:"currentTermID,omitempty"`
	LogData              []byte               `protobuf:"bytes,3,opt,name=logData,proto3" json:"logData,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApplyLogRequest) Reset()         { *m = ApplyLogRequest{} }
func (m *ApplyLogRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyLogRequest) ProtoMessage()    {}
func (*ApplyLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{0}
}
func (m *ApplyLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLogRequest.Unmarshal(m, b)
}
func (m *ApplyLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLogRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLogRequest.Merge(dst, src)
}
func (m *ApplyLogRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyLogRequest.Size(m)
}
func (m *ApplyLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLogRequest proto.InternalMessageInfo

func (m *ApplyLogRequest) GetCurrentCommitID() int64 {
	if m != nil {
		return m.CurrentCommitID
	}
	return 0
}

func (m *ApplyLogRequest) GetCurrentTermID() int64 {
	if m != nil {
		return m.CurrentTermID
	}
	return 0
}

func (m *ApplyLogRequest) GetLogData() []byte {
	if m != nil {
		return m.LogData
	}
	return nil
}

func (m *ApplyLogRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type ApplyLogResponse struct {
	CurrentCommitID      int64                `protobuf:"varint,1,opt,name=currentCommitID" json:"currentCommitID,omitempty"`
	CurrentTermID        int64                `protobuf:"varint,2,opt,name=currentTermID" json:"currentTermID,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApplyLogResponse) Reset()         { *m = ApplyLogResponse{} }
func (m *ApplyLogResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyLogResponse) ProtoMessage()    {}
func (*ApplyLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{1}
}
func (m *ApplyLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLogResponse.Unmarshal(m, b)
}
func (m *ApplyLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLogResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLogResponse.Merge(dst, src)
}
func (m *ApplyLogResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyLogResponse.Size(m)
}
func (m *ApplyLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLogResponse proto.InternalMessageInfo

func (m *ApplyLogResponse) GetCurrentCommitID() int64 {
	if m != nil {
		return m.CurrentCommitID
	}
	return 0
}

func (m *ApplyLogResponse) GetCurrentTermID() int64 {
	if m != nil {
		return m.CurrentTermID
	}
	return 0
}

func (m *ApplyLogResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type HeartbeatRequest struct {
	TermIndex            int64                `protobuf:"varint,1,opt,name=termIndex" json:"termIndex,omitempty"`
	LastTermIndex        int64                `protobuf:"varint,2,opt,name=lastTermIndex" json:"lastTermIndex,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{2}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (dst *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(dst, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetTermIndex() int64 {
	if m != nil {
		return m.TermIndex
	}
	return 0
}

func (m *HeartbeatRequest) GetLastTermIndex() int64 {
	if m != nil {
		return m.LastTermIndex
	}
	return 0
}

func (m *HeartbeatRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	TermIndex            int64                `protobuf:"varint,1,opt,name=termIndex" json:"termIndex,omitempty"`
	LastTermIndex        int64                `protobuf:"varint,2,opt,name=lastTermIndex" json:"lastTermIndex,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{3}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (dst *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(dst, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetTermIndex() int64 {
	if m != nil {
		return m.TermIndex
	}
	return 0
}

func (m *HeartbeatResponse) GetLastTermIndex() int64 {
	if m != nil {
		return m.LastTermIndex
	}
	return 0
}

func (m *HeartbeatResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type VoteRequest struct {
	RequestNodeID        int64    `protobuf:"varint,1,opt,name=RequestNodeID" json:"RequestNodeID,omitempty"`
	LastCommitID         int64    `protobuf:"varint,2,opt,name=LastCommitID" json:"LastCommitID,omitempty"`
	LastTerm             int64    `protobuf:"varint,3,opt,name=LastTerm" json:"LastTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{4}
}
func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (dst *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(dst, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetRequestNodeID() int64 {
	if m != nil {
		return m.RequestNodeID
	}
	return 0
}

func (m *VoteRequest) GetLastCommitID() int64 {
	if m != nil {
		return m.LastCommitID
	}
	return 0
}

func (m *VoteRequest) GetLastTerm() int64 {
	if m != nil {
		return m.LastTerm
	}
	return 0
}

type VoteResponse struct {
	ResponseNodeID       int64    `protobuf:"varint,1,opt,name=ResponseNodeID" json:"ResponseNodeID,omitempty"`
	VoteState            int64    `protobuf:"varint,2,opt,name=VoteState" json:"VoteState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{5}
}
func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (dst *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(dst, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetResponseNodeID() int64 {
	if m != nil {
		return m.ResponseNodeID
	}
	return 0
}

func (m *VoteResponse) GetVoteState() int64 {
	if m != nil {
		return m.VoteState
	}
	return 0
}

type SnapshotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{6}
}
func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRequest.Unmarshal(m, b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(dst, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotRequest.Size(m)
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

type SnapshotResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_8a90809919e43bd1, []int{7}
}
func (m *SnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotResponse.Unmarshal(m, b)
}
func (m *SnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotResponse.Marshal(b, m, deterministic)
}
func (dst *SnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResponse.Merge(dst, src)
}
func (m *SnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotResponse.Size(m)
}
func (m *SnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApplyLogRequest)(nil), "protobuffer.ApplyLogRequest")
	proto.RegisterType((*ApplyLogResponse)(nil), "protobuffer.ApplyLogResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "protobuffer.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "protobuffer.HeartbeatResponse")
	proto.RegisterType((*VoteRequest)(nil), "protobuffer.VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "protobuffer.VoteResponse")
	proto.RegisterType((*SnapshotRequest)(nil), "protobuffer.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "protobuffer.SnapshotResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogApplay service

type LogApplayClient interface {
	ApplyLog(ctx context.Context, in *ApplyLogRequest, opts ...grpc.CallOption) (*ApplyLogResponse, error)
}

type logApplayClient struct {
	cc *grpc.ClientConn
}

func NewLogApplayClient(cc *grpc.ClientConn) LogApplayClient {
	return &logApplayClient{cc}
}

func (c *logApplayClient) ApplyLog(ctx context.Context, in *ApplyLogRequest, opts ...grpc.CallOption) (*ApplyLogResponse, error) {
	out := new(ApplyLogResponse)
	err := grpc.Invoke(ctx, "/protobuffer.LogApplay/ApplyLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogApplay service

type LogApplayServer interface {
	ApplyLog(context.Context, *ApplyLogRequest) (*ApplyLogResponse, error)
}

func RegisterLogApplayServer(s *grpc.Server, srv LogApplayServer) {
	s.RegisterService(&_LogApplay_serviceDesc, srv)
}

func _LogApplay_ApplyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogApplayServer).ApplyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuffer.LogApplay/ApplyLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogApplayServer).ApplyLog(ctx, req.(*ApplyLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogApplay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuffer.LogApplay",
	HandlerType: (*LogApplayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyLog",
			Handler:    _LogApplay_ApplyLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

// Client API for Snapshots service

type SnapshotsClient interface {
	RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
}

type snapshotsClient struct {
	cc *grpc.ClientConn
}

func NewSnapshotsClient(cc *grpc.ClientConn) SnapshotsClient {
	return &snapshotsClient{cc}
}

func (c *snapshotsClient) RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := grpc.Invoke(ctx, "/protobuffer.Snapshots/RequestSnapshot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Snapshots service

type SnapshotsServer interface {
	RequestSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
}

func RegisterSnapshotsServer(s *grpc.Server, srv SnapshotsServer) {
	s.RegisterService(&_Snapshots_serviceDesc, srv)
}

func _Snapshots_RequestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotsServer).RequestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuffer.Snapshots/RequestSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotsServer).RequestSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snapshots_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuffer.Snapshots",
	HandlerType: (*SnapshotsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestSnapshot",
			Handler:    _Snapshots_RequestSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

// Client API for LeaderElection service

type LeaderElectionClient interface {
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type leaderElectionClient struct {
	cc *grpc.ClientConn
}

func NewLeaderElectionClient(cc *grpc.ClientConn) LeaderElectionClient {
	return &leaderElectionClient{cc}
}

func (c *leaderElectionClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := grpc.Invoke(ctx, "/protobuffer.LeaderElection/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LeaderElection service

type LeaderElectionServer interface {
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
}

func RegisterLeaderElectionServer(s *grpc.Server, srv LeaderElectionServer) {
	s.RegisterService(&_LeaderElection_serviceDesc, srv)
}

func _LeaderElection_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuffer.LeaderElection/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeaderElection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuffer.LeaderElection",
	HandlerType: (*LeaderElectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _LeaderElection_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

// Client API for HeartBeats service

type HeartBeatsClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type heartBeatsClient struct {
	cc *grpc.ClientConn
}

func NewHeartBeatsClient(cc *grpc.ClientConn) HeartBeatsClient {
	return &heartBeatsClient{cc}
}

func (c *heartBeatsClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := grpc.Invoke(ctx, "/protobuffer.HeartBeats/heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HeartBeats service

type HeartBeatsServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

func RegisterHeartBeatsServer(s *grpc.Server, srv HeartBeatsServer) {
	s.RegisterService(&_HeartBeats_serviceDesc, srv)
}

func _HeartBeats_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartBeatsServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuffer.HeartBeats/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartBeatsServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeartBeats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuffer.HeartBeats",
	HandlerType: (*HeartBeatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "heartbeat",
			Handler:    _HeartBeats_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_raft_8a90809919e43bd1) }

var fileDescriptor_raft_8a90809919e43bd1 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb5, 0x04, 0x41, 0x3d, 0x49, 0x9b, 0x74, 0x4f, 0xc6, 0x2a, 0x10, 0x59, 0x15, 0xca,
	0xc9, 0x95, 0xca, 0x85, 0x2b, 0x25, 0x08, 0x8a, 0xac, 0x1e, 0x5c, 0x0b, 0x21, 0x71, 0xda, 0x34,
	0x13, 0x37, 0x92, 0xed, 0x35, 0xbb, 0x13, 0x89, 0xbe, 0x05, 0xdc, 0x79, 0x0d, 0xde, 0x0f, 0xd9,
	0xde, 0x8d, 0xb3, 0x56, 0x73, 0x40, 0x20, 0xf5, 0xe4, 0xdd, 0xff, 0x7c, 0xfd, 0x3c, 0x33, 0x0b,
	0xa0, 0xc4, 0x8a, 0xa2, 0x4a, 0x49, 0x92, 0x7c, 0xd8, 0x7c, 0x16, 0x9b, 0xd5, 0x0a, 0x55, 0xf0,
	0x32, 0x93, 0x32, 0xcb, 0xf1, 0xcc, 0x6a, 0x67, 0xb4, 0x2e, 0x50, 0x93, 0x28, 0xaa, 0xd6, 0x3b,
	0xfc, 0xcd, 0x60, 0xfc, 0xb6, 0xaa, 0xf2, 0xbb, 0x58, 0x66, 0x09, 0x7e, 0xdb, 0xa0, 0x26, 0x3e,
	0x83, 0xf1, 0xcd, 0x46, 0x29, 0x2c, 0xe9, 0x9d, 0x2c, 0x8a, 0x35, 0x5d, 0xce, 0x7d, 0x36, 0x65,
	0xb3, 0x41, 0xd2, 0x97, 0xf9, 0x29, 0x1c, 0x1a, 0x29, 0x45, 0x55, 0x5c, 0xce, 0xfd, 0x47, 0x8d,
	0x9f, 0x2b, 0x72, 0x1f, 0x9e, 0xe6, 0x32, 0x9b, 0x0b, 0x12, 0xfe, 0x60, 0xca, 0x66, 0xa3, 0xc4,
	0x5e, 0xf9, 0x1b, 0xf0, 0xb6, 0x40, 0xfe, 0xe3, 0x29, 0x9b, 0x0d, 0xcf, 0x83, 0xa8, 0x45, 0x8e,
	0x2c, 0x72, 0x94, 0x5a, 0x8f, 0xa4, 0x73, 0x0e, 0x7f, 0x31, 0x98, 0x74, 0xdc, 0xba, 0x92, 0xa5,
	0xc6, 0xff, 0x0e, 0xee, 0xe0, 0x0d, 0xfe, 0x06, 0xef, 0x07, 0x83, 0xc9, 0x47, 0x14, 0x8a, 0x16,
	0x28, 0xc8, 0xf6, 0xf5, 0x04, 0x3c, 0xaa, 0x13, 0x97, 0x4b, 0xfc, 0x6e, 0xc0, 0x3a, 0xa1, 0x46,
	0xca, 0x85, 0x6e, 0x4b, 0x37, 0x1e, 0x06, 0xc9, 0x11, 0xff, 0x01, 0xe9, 0x27, 0x83, 0xe3, 0x1d,
	0x24, 0xd3, 0xb2, 0x87, 0x65, 0xd2, 0x30, 0xfc, 0x2c, 0x09, 0x6d, 0x83, 0x4e, 0xe1, 0xd0, 0x1c,
	0xaf, 0xe4, 0x12, 0xb7, 0xd3, 0x73, 0x45, 0x1e, 0xc2, 0x28, 0x16, 0xba, 0x1b, 0x71, 0xcb, 0xe4,
	0x68, 0x3c, 0x80, 0x83, 0xd8, 0x30, 0x36, 0x44, 0x83, 0x64, 0x7b, 0x0f, 0x53, 0x18, 0xb5, 0x45,
	0x4d, 0x0b, 0x5e, 0xc1, 0x91, 0x3d, 0x3b, 0x65, 0x7b, 0x6a, 0xdd, 0xaa, 0x3a, 0xee, 0x9a, 0x04,
	0xa1, 0x29, 0xda, 0x09, 0xe1, 0x31, 0x8c, 0xaf, 0x4b, 0x51, 0xe9, 0x5b, 0x69, 0xe7, 0x1d, 0x72,
	0x98, 0x74, 0x52, 0x9b, 0xea, 0x3c, 0x05, 0x2f, 0x96, 0x59, 0xbd, 0xb9, 0xe2, 0x8e, 0x7f, 0x80,
	0x03, 0xbb, 0xc3, 0xfc, 0x24, 0xda, 0x79, 0xb7, 0x51, 0xef, 0x49, 0x06, 0xcf, 0xf7, 0x58, 0x4d,
	0xd6, 0xaf, 0xe0, 0xd9, 0x4a, 0x9a, 0x5f, 0xc1, 0xd8, 0x84, 0x59, 0xad, 0x97, 0xbc, 0xc7, 0xd9,
	0x4b, 0x7e, 0x0f, 0xf2, 0x51, 0x8c, 0x62, 0x89, 0xea, 0x7d, 0x8e, 0x37, 0xb4, 0x96, 0x25, 0xbf,
	0x80, 0xa1, 0x89, 0xad, 0xff, 0x9f, 0xfb, 0x4e, 0xfc, 0xce, 0x40, 0x83, 0x67, 0xf7, 0x58, 0x4c,
	0xd6, 0x2f, 0x00, 0xcd, 0x36, 0x5e, 0xa0, 0x20, 0xcd, 0x3f, 0x81, 0x77, 0x6b, 0x77, 0x93, 0xbb,
	0x3c, 0xfd, 0x67, 0x14, 0xbc, 0xd8, 0x67, 0x6e, 0x33, 0x2f, 0x9e, 0x34, 0xe6, 0xd7, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xf3, 0xa4, 0x8c, 0x15, 0x05, 0x00, 0x00,
}
